manifest:
  remotes:
    - name: allymparker
      url-base: https://github.com/allymparker
  projects:
    - name: zmk
      remote: allymparker
      revision: main
      import: app/west.yml
  self:
    path: config
