services:
  zmk-build:
    container_name: zmk-build
    image: zmkfirmware/zmk-build-arm:3.5-branch
    security_opt:
      - label=disable
    working_dir: /keymap
    volumes:
      - .:/keymap
    stdin_open: true
    tty: true