layers:
  Base: ['&kp C_VOL_UP', '&kp Q', '&kp W', '&kp E', '&kp R', '&kp T', '&kp Y', '&kp U', '&kp I', '&kp O', '&kp P', $$zoom-in$$, '&kp C_PP', '&hm_l LCTRL A', '&hm_l
      LALT S', '&hm_l LGUI D', '&hm_l LSHIFT F', '&kp G', '&kp H', '&hm_r LSHIFT J', '&hm_r LGUI K', '&hm_r LALT L', '&hm_r LCTRL SEMI', $$screenshot$$, '&kp C_VOL_DN',
    '&kp Z', '&kp X', '&kp C', '&lt 10 V', '&kp B', '&kp N', '&lt 11 M', '&kp COMMA', '&kp DOT', '&kp FSLH', $$zoom-out$$, '&lt 5 TAB', '&lt 3 RET', '&lt 2 ESC',
    '&lt 4 BSPC', '&lt 1 SPC', '&kp DEL']
  Symbol: ['&kp C_NEXT', '&kp CARET', '&kp AMPS', '&kp HASH', '&kp TILDE', '&kp LPAR', '&kp RPAR', '&trans', '&trans', '&trans', '&trans', '&trans', '&kp C_STOP',
    '&kp GRAVE', '&kp PIPE', '&kp EXCL', '&kp SQT', '&kp LBRC', '&kp RBRC', '&trans', '&trans', '&trans', '&trans', '&trans', '&kp C_PREV', '&kp BSLH', '&kp AT',
    '&kp DLLR', '#', '&kp LBKT', '&kp RBKT', '&trans', '&trans', '&trans', '&trans', '&trans', '&kp UNDER', '&kp MINUS', '&kp DQT', '&trans', '&trans', '&trans']
  Nav: ['&kp C_NEXT', '&kp F16', '&kp F17', '&TD_Maximise', '&TD_Right', '&trans', App Next, Word Left, Word Right, '&kp PG_UP', '&trans', '&trans', '&kp C_STOP',
    $$undo$$, $$cut$$, '&hm_l LGUI LG(C)', '&hm_l LSHIFT LG(V)', Caps Wrd, '&kp LEFT', '&kp DOWN', '&kp UP', '&kp RIGHT', '&trans', '&trans', '&kp C_PREV', '&trans',
    '&trans', '&trans', '&trans', '&trans', Win Next, Home, End, '&kp PG_DN', '&trans', '&trans', '&trans', '&trans', '&trans', Delete Word, $$search$$, '&trans']
  Num: ['&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&kp STAR', '&kp N7', '&kp N8', '&kp N9', '&trans', '&trans', '&trans', '&kp LCTRL', '&kp LALT',
    '&kp LGUI', '&kp LSHFT', '&trans', '&kp PLUS', '&kp N4', '&kp N5', '&kp N6', '&kp FSLH', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans',
    '&kp MINUS', '&kp N1', '&kp N2', '&kp N3', '&kp PRCNT', '&trans', '&trans', '&trans', '&trans', '&kp EQUAL', '&kp N0', '&kp DOT']
  Func: ['&trans', '&kp F9', '&kp F10', '&kp F11', '&kp F12', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&kp F5', '&kp F6',
    Step Into, Step Over, '&trans', '&trans', '&kp LSHFT', '&kp LCTRL', '&kp LALT', '&kp LGUI', '&trans', '&trans', '&kp F1', '&kp F2', '&kp F3', '&kp F4', '&trans',
    '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans']
  Media: [Boot, '&trans', '&trans', '&trans', '&trans', '&trans', Boot, '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans',
    '&trans', '&trans', '&kp C_PREV', '&kp C_VOL_DN', '&kp C_VOL_UP', '&kp C_NEXT', '&trans', '&trans', '&bt BT_CLR', BT 1, BT 2, BT 3, '&trans', '&trans', '&trans',
    '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&kp C_MUTE', '&kp C_PP', '&kp C_STOP']
  Jetbrains: ['&trans', '&trans', '&trans', '&trans', '&sl 7', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans',
    '&to 9', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&sl 8',
    '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&trans', '&to 0', '&trans', '&trans', '&trans']
  Refactor: ['&none', '&none', '&none', '&none', Rename, This, '&none', '&none', Inline, '&none', Extract Parameter, '&none', '&none', '&none', Change Signature,
    Safe Delete, Extract Field, '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', Extract Constant, Extract Variable, '&none',
    Inline, Extract Method, '&none', '&none', '&none', '&none', '&none', '&none', '&to 0', '&none', '&none', '&none']
  Code Nav: ['&none', '&none', '&none', '&none', '&none', Type, '&none', Find Usages, '&none', '&none', '&none', '&none', '&none', '&none', '&none', Declaration,
    '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none',
    '&none', '&none', '&none', '&none', '&to 0', '&none', '&none', '&none']
  Debug: ['&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none',
    '&none', Resume, Step Into, Step Out, Step Over, '&none', '&none', '&none', '&none', '&none', '&none', '&none', Breakpoint, '&none', '&none', '&none', '&none',
    '&none', '&none', '&none', '&none', '&to 0', Build Project, '&none', '&none']
  Fwd: ['&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none',
    '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', Forward, '&none', '&none', '&none', '&none',
    '&none', '&none', '&none', '&none', '&none', '&none']
  Bck: ['&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none',
    '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', '&none', Back, '&none', '&none', '&none', '&none', '&none', '&none', '&none',
    '&none', '&none', '&none', '&none', '&none', '&none']
combos:
- p: [33, 34]
  k: ../
  l: [Base]
- p: [21, 22]
  k: $$screenshot$$
  l: [Base]
- p: [2, 1]
  k: '&kp C_VOL_UP'
  l: [Base]
- p: [14, 13]
  k: '&kp C_PP'
  l: [Base]
- p: [26, 25]
  k: '&kp C_VOL_DN'
  l: [Base]
- p: [28, 31]
  k: '&sl 6'
  l: [Base]
  a: bottom
