layers:
  Base:
  - $$vol-up$$
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - $$zoom-in$$
  - $$play-pause$$
  - {t: A, h: $$apple-keyboard-control$$}
  - {t: S, h: $$apple-keyboard-option$$}
  - {t: D, h: $$apple-keyboard-command$$}
  - {t: F, h: $$apple-keyboard-shift$$}
  - G
  - H
  - {t: J, h: $$apple-keyboard-shift$$}
  - {t: K, h: $$apple-keyboard-command$$}
  - {t: L, h: $$apple-keyboard-option$$}
  - {t: ;, h: $$apple-keyboard-control$$}
  - $$screenshot$$
  - $$vol-down$$
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - $$zoom-out$$
  - {t: ↹, h: Media}
  - {t: ⏎, h: Num}
  - {t: esc, h: Nav}
  - {t: ⌫, h: Func}
  - {t: ␣, h: Symbol}
  - ⌦
  Symbol:
  - $$play-next$$
  - ^
  - '&'
  - £
  - '~'
  - (
  - )
  - ''
  - ''
  - ''
  - ''
  - ''
  - $$stop$$
  - '`'
  - '|'
  - '!'
  - ''''
  - '{'
  - '}'
  - ''
  - ''
  - ''
  - ''
  - ''
  - $$play-prev$$
  - \
  - '@'
  - $
  - '#'
  - '['
  - ']'
  - ''
  - ''
  - ''
  - ''
  - ''
  - _
  - '-'
  - '"'
  - ''
  - {type: held}
  - ''
  Nav:
  - $$play-next$$
  - F16
  - F17
  - '&TD_Maximise'
  - '&TD_Right'
  - ''
  - App Next
  - Word Left
  - Word Right
  - Page Up
  - ''
  - ''
  - $$stop$$
  - $$undo$$
  - $$cut$$
  - $$copy$$
  - {t: $$paste$$, h: $$apple-keyboard-shift$$}
  - Caps Wrd
  - ←
  - ↓
  - ↑
  - →
  - ''
  - ''
  - $$play-prev$$
  - ''
  - ''
  - ''
  - ''
  - ''
  - Win Next
  - Home
  - End
  - Page Down
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - Delete Word
  - $$search$$
  - ''
  Num:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '*'
  - '7'
  - '8'
  - '9'
  - ''
  - ''
  - ''
  - $$apple-keyboard-control$$
  - $$apple-keyboard-option$$
  - $$apple-keyboard-command$$
  - $$apple-keyboard-shift$$
  - ''
  - +
  - '4'
  - '5'
  - '6'
  - /
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '-'
  - '1'
  - '2'
  - '3'
  - '%'
  - ''
  - ''
  - {t: Num, h: toggle, type: held}
  - {t: Num, h: toggle}
  - '='
  - '0'
  - .
  Func:
  - ''
  - F9
  - F10
  - F11
  - F12
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - F5
  - F6
  - Step Into
  - Step Over
  - ''
  - ''
  - $$apple-keyboard-shift$$
  - $$apple-keyboard-control$$
  - $$apple-keyboard-option$$
  - $$apple-keyboard-command$$
  - ''
  - ''
  - F1
  - F2
  - F3
  - F4
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  Media:
  - Boot
  - ''
  - ''
  - ''
  - ''
  - ''
  - Boot
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - $$play-prev$$
  - $$vol-down$$
  - $$vol-up$$
  - $$play-next$$
  - ''
  - ''
  - BT CLR
  - BT 1
  - BT 2
  - BT 3
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  - $$mute$$
  - $$play-pause$$
  - $$stop$$
  Jetbrains:
  - ''
  - ''
  - ''
  - ''
  - {t: Refactor, h: sticky}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: Code Debug, h: sticky}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: Code Nav, h: sticky}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: Base, h: toggle}
  - ''
  - ''
  - ''
  Refactor:
  - ''
  - ''
  - ''
  - ''
  - {t: Rename, type: held}
  - This
  - ''
  - ''
  - Inline
  - ''
  - Extract Parameter
  - ''
  - ''
  - ''
  - Change Signature
  - Safe Delete
  - Extract Field
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - Extract Constant
  - Extract Variable
  - ''
  - ''
  - Inline
  - Extract Method
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: Base, h: toggle}
  - ''
  - ''
  - ''
  Code Nav:
  - ''
  - ''
  - ''
  - ''
  - ''
  - Type
  - ''
  - Find Usages
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - Declaration
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: Base, h: toggle}
  - ''
  - ''
  - ''
  Code Debug:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  - Resume
  - Step Into
  - Step Out
  - Step Over
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: Base, h: toggle}
  - Build Project
  - ''
  - ''
combos:
- p: [33, 34]
  k: ../
  l: [Base]
- p: [28, 31]
  k: JB
  l: [Base]
  a: bottom
