layout: {zmk_keyboard: base}
layers:
  Base:
  - VOL UP
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - Gui++
  - PP
  - {t: A, h: LCTRL}
  - {t: S, h: LALT}
  - {t: D, h: LGUI}
  - {t: F, h: LSHIFT}
  - G
  - H
  - {t: J, h: LSHIFT}
  - {t: K, h: LGUI}
  - {t: L, h: LALT}
  - {t: ;, h: LCTRL}
  - Sft+Gui+Ctl+4
  - VOL DN
  - Z
  - X
  - C
  - {t: V, h: Fwd}
  - B
  - N
  - {t: M, h: Bck}
  - ','
  - .
  - /
  - Gui+-
  - {t: TAB, h: Media}
  - {t: RET, h: Num}
  - {t: ESC, h: Nav}
  - {t: BSPC, h: Func}
  - {t: SPC, h: Symbol}
  - DEL
  Symbol:
  - NEXT
  - ^
  - '&'
  - '#'
  - '~'
  - (
  - )
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - STOP
  - '`'
  - '|'
  - '!'
  - ''''
  - '{'
  - '}'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - PREV
  - \
  - '@'
  - $
  - Alt+3
  - '['
  - ']'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - _
  - '-'
  - '"'
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  Nav:
  - '&bootloader'
  - F16
  - F17
  - '&TD_Maximise'
  - '&TD_Right'
  - {t: ▽, type: trans}
  - '&SW_APP'
  - Alt+LEFT
  - Alt+RIGHT
  - PG UP
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Gui+Z
  - Gui+X
  - {t: Gui+C, h: LGUI}
  - {t: Gui+V, h: LSHIFT}
  - '&TD_Caps'
  - LEFT
  - DOWN
  - UP
  - RIGHT
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&SW_TAB'
  - Gui+LEFT
  - Gui+RIGHT
  - PG DN
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - Alt+BSPC
  - Gui+SPC
  - {t: ▽, type: trans}
  Num:
  - NEXT
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '*'
  - '7'
  - '8'
  - '9'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - LCTRL
  - LALT
  - LGUI
  - LSHFT
  - {t: ▽, type: trans}
  - +
  - '4'
  - '5'
  - '6'
  - /
  - {t: ▽, type: trans}
  - PREV
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '-'
  - '1'
  - '2'
  - '3'
  - '%'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - '='
  - '0'
  - .
  Func:
  - {t: ▽, type: trans}
  - F9
  - F10
  - F11
  - F12
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&bootloader'
  - {t: ▽, type: trans}
  - F5
  - F6
  - F7
  - F8
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - LSHFT
  - LCTRL
  - LALT
  - LGUI
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - F1
  - F2
  - F3
  - F4
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  Media:
  - '&bootloader'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - BT CLR
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  Jetbrains:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: Refactor, h: sticky}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: Debug, h: toggle}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: Code Nav, h: sticky}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: Base, h: toggle}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  Refactor:
  - ''
  - ''
  - ''
  - ''
  - {t: Sft+F6, type: held}
  - Ctl+T
  - ''
  - ''
  - Alt+Gui+N
  - ''
  - Alt+Gui+P
  - ''
  - ''
  - ''
  - Gui+F6
  - Gui+DEL
  - Alt+Gui+F
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - Alt+Gui+C
  - Alt+Gui+V
  - ''
  - Alt+Gui+N
  - Alt+Gui+M
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: Base, h: toggle}
  - ''
  - ''
  - ''
  Code Nav:
  - ''
  - ''
  - ''
  - ''
  - ''
  - Sft+Gui+B
  - ''
  - Alt+F7
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - Gui+B
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: Base, h: toggle}
  - ''
  - Gui+F12
  - ''
  Debug:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - Alt+Gui+R
  - F7
  - Sft+F8
  - F8
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - Gui+F8
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: Base, h: toggle}
  - Gui+F9
  - ''
  - ''
  Fwd:
  - ''
  - '&bootloader'
  - ''
  - ''
  - ''
  - ''
  - ''
  - Alt+F7
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  - Gui+]
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  Bck:
  - ''
  - ''
  - ''
  - ''
  - Sft+F6
  - ''
  - ''
  - ''
  - ''
  - ''
  - '&bootloader'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - Gui+[
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
combos:
- p: [33, 34]
  k: '&UPDIR'
  l: [Base]
- p: [9, 10]
  k: Gui++
  l: [Base]
- p: [21, 22]
  k: Sft+Gui+Ctl+4
  l: [Base]
- p: [8, 9]
  k: Gui+-
  l: [Base]
- p: [4, 5]
  k: VOL UP
  l: [Base]
- p: [16, 17]
  k: PP
  l: [Base]
- p: [28, 29]
  k: VOL DN
  l: [Base]
- p: [16, 17]
  k: NEXT
  l: [Nav]
- p: [28, 29]
  k: PREV
  l: [Nav]
- p: [28, 31]
  k: {t: Jetbrains, h: sticky}
  l: [Base]
