layers:
  Base:
  - $$vol-up$$
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - $$zoom-in$$
  - $$play-pause$$
  - {t: A, h: $$apple-keyboard-control$$}
  - {t: S, h: $$apple-keyboard-option$$}
  - {t: D, h: $$apple-keyboard-command$$}
  - {t: F, h: $$apple-keyboard-shift$$}
  - G
  - H
  - {t: J, h: $$apple-keyboard-shift$$}
  - {t: K, h: $$apple-keyboard-command$$}
  - {t: L, h: $$apple-keyboard-option$$}
  - {t: ;, h: $$apple-keyboard-control$$}
  - $$screenshot$$
  - $$vol-down$$
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - $$zoom-out$$
  - {t: ↹, h: media}
  - {t: ⏎, h: num}
  - {t: esc, h: nav}
  - {t: ⌫, h: fun}
  - {t: ␣, h: symbol}
  - ⌦
  symbol:
  - $$play-next$$
  - ^
  - '&'
  - £
  - '~'
  - (
  - )
  - ''
  - ''
  - ''
  - ''
  - ''
  - $$stop$$
  - '`'
  - '|'
  - '!'
  - ''''
  - '{'
  - '}'
  - ''
  - ''
  - ''
  - ''
  - ''
  - $$play-prev$$
  - \
  - '@'
  - $
  - '#'
  - '['
  - ']'
  - ''
  - ''
  - ''
  - ''
  - ''
  - _
  - '-'
  - '"'
  - ''
  - {type: held}
  - ''
  nav:
  - $$play-next$$
  - F16
  - F17
  - '&TD_Maximise'
  - F19
  - ''
  - App Next
  - Word Left
  - Word Right
  - Page Up
  - ''
  - ''
  - $$stop$$
  - $$undo$$
  - $$cut$$
  - $$copy$$
  - {t: $$paste$$, h: $$apple-keyboard-shift$$}
  - Caps Wrd
  - ←
  - ↓
  - ↑
  - →
  - ''
  - ''
  - $$play-prev$$
  - ''
  - ''
  - ''
  - ''
  - ''
  - Win Next
  - Home
  - End
  - Page Down
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - Delete Word
  - $$search$$
  - ''
  num:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '*'
  - '7'
  - '8'
  - '9'
  - ''
  - ''
  - ''
  - $$apple-keyboard-control$$
  - $$apple-keyboard-option$$
  - $$apple-keyboard-command$$
  - $$apple-keyboard-shift$$
  - ''
  - +
  - '4'
  - '5'
  - '6'
  - /
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '-'
  - '1'
  - '2'
  - '3'
  - '%'
  - ''
  - ''
  - {t: num, h: toggle, type: held}
  - {t: num, h: toggle}
  - '='
  - '0'
  - .
  fun:
  - ''
  - F9
  - F10
  - F11
  - F12
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - F5
  - F6
  - F7
  - F8
  - ''
  - ''
  - $$apple-keyboard-shift$$
  - $$apple-keyboard-control$$
  - $$apple-keyboard-option$$
  - $$apple-keyboard-command$$
  - ''
  - ''
  - F1
  - F2
  - F3
  - F4
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  media:
  - Boot
  - ''
  - ''
  - ''
  - ''
  - ''
  - Boot
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - $$play-prev$$
  - $$vol-down$$
  - $$vol-up$$
  - $$play-next$$
  - ''
  - ''
  - BT CLR
  - BT 1
  - BT 2
  - BT 3
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  - $$mute$$
  - $$play-pause$$
  - $$stop$$
combos:
- p: [33, 34]
  k: ../
