manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: allymparker
      url-base: https://github.com/allymparker
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-tri-state
      remote: allymparker
      revision: main
      path: modules/zmk/tri-state
    - name: zmk-rgbled-widget
      remote: allymparker
      revision: main
  self:
    path: config
