manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/allymparker
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: allymparker/corneroll
      import: app/west.yml
  self:
    path: config
