on:
  push:
    paths-ignore:
      - ".github/workflows/keymap-drawer.yml"
      - "keymap-drawer/*"
      - "README.md"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        target: [corne]
        # target: [corneroll, corne, zen]
    uses: LOWPROKB/zmk/.github/workflows/build-user-config.yml@corne-ish-zen-v2
    with:
      build_matrix_path: "build_${{ matrix.target }}.yaml"
      config_path: "config_${{ matrix.target }}"
      archive_name: "${{ matrix.target }}"
