name: Build Firmware
on:
  push:
    paths-ignore:
      - ".github/workflows/keymap-drawer.yml"
      - ".github/workflows/corneroll.yml"
      - "keymap-drawer/*"
      - "README.md"
      - "config_corneroll"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        # target: [corneroll]
        target: [zen]
    uses: allymparker/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: "build_${{ matrix.target }}.yaml"
      config_path: "config_${{ matrix.target }}"
      archive_name: "${{ matrix.target }}"
