on: [push, pull_request, create, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: config/
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            config/modules/
            config/tools/
            config/zephyr/
            config/bootloader/
            config/zmk/
          key: ${{ runner.os }}-build-v2-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Initialize workspace (west init)
        run: west init -l config/config_corneroll
      - name: Update modules (west update)
        run: west update
        working-directory: config
      - name: Export zephyr CMake package (west zephyr-export)
        run: west zephyr-export
        working-directory: config
      - name: List modules (west list)
        run: west list
        working-directory: config
      - name: Build Corneroll (west build)
        run: west build -s zmk/app -b nice_nano -d build/corneroll -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config/config_corneroll" -DSHIELD="corneroll_left nice_view_adapter nice_view"
        working-directory: config
      - name: Corneroll .config
        if: ${{ always() }}
        run: cat -n build/corneroll/zephyr/.config
        working-directory: config
      - name: Rename zmk.uf2
        run: |
          cp build/corneroll/zephyr/zmk.uf2 corneroll.uf2
        working-directory: config
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: "*.uf2"
