# Example for using the keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "base/*"
      - "keymap-drawer/config.yaml"
      - ".github/workflows/keymap-drawer.yml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write # allow workflow to commit to the repo
    with:
      keymap_patterns: "base/*.keymap"
      west_config_path: "config_charma"
      config_path: "keymap-drawer/config.yaml"
      output_folder: "keymap-drawer"
      draw_args: "base:'-k corne_rotated -l LAYOUT_split_3x6_3'"
